version: "3.8"

services:
  postgres:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD: please
    networks:
      - web
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  web:
    driver: bridge

volumes:
  postgres_data:
